create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  consultation_id text not null,
  event_type text not null check (event_type in ('engine_request', 'consultation_completed', 'safety_block')),
  source text,
  created_at timestamptz not null default now()
);

create index if not exists product_events_user_created_idx
  on public.product_events (user_id, created_at desc);

create index if not exists product_events_consultation_idx
  on public.product_events (user_id, consultation_id);

create index if not exists product_events_type_idx
  on public.product_events (event_type, created_at desc);

alter table public.product_events enable row level security;

drop policy if exists "users can read own product events" on public.product_events;
create policy "users can read own product events"
  on public.product_events
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "users can insert own product events" on public.product_events;
create policy "users can insert own product events"
  on public.product_events
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);
