create table if not exists public.user_credit_wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 0 check (balance >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.stripe_credit_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  checkout_session_id text not null unique,
  payment_intent_id text,
  price_id text not null,
  credits integer not null check (credits > 0),
  amount_total integer,
  currency text,
  status text not null default 'paid',
  created_at timestamptz not null default now()
);

create index if not exists stripe_credit_purchases_user_created_idx
  on public.stripe_credit_purchases (user_id, created_at desc);

alter table public.user_credit_wallets enable row level security;
alter table public.stripe_credit_purchases enable row level security;

create policy "users can read own credit wallet"
  on public.user_credit_wallets
  for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "users can read own stripe purchases"
  on public.stripe_credit_purchases
  for select to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.apply_stripe_credit_purchase(
  p_user_id uuid,
  p_checkout_session_id text,
  p_payment_intent_id text,
  p_price_id text,
  p_credits integer,
  p_amount_total integer,
  p_currency text
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
begin
  if p_credits < 1 then
    raise exception 'INVALID_CREDITS';
  end if;

  insert into public.stripe_credit_purchases (
    user_id, checkout_session_id, payment_intent_id, price_id,
    credits, amount_total, currency, status
  ) values (
    p_user_id, p_checkout_session_id, p_payment_intent_id, p_price_id,
    p_credits, p_amount_total, lower(p_currency), 'paid'
  )
  on conflict (checkout_session_id) do nothing;

  if not found then
    select balance into v_balance
    from public.user_credit_wallets
    where user_id = p_user_id;
    return coalesce(v_balance, 0);
  end if;

  insert into public.user_credit_wallets (user_id, balance)
  values (p_user_id, p_credits)
  on conflict (user_id)
  do update set
    balance = public.user_credit_wallets.balance + excluded.balance,
    updated_at = now()
  returning balance into v_balance;

  return v_balance;
end;
$$;

create or replace function public.consume_paid_credit(p_user_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance integer;
begin
  update public.user_credit_wallets
  set balance = balance - 1,
      updated_at = now()
  where user_id = p_user_id
    and balance > 0
  returning balance into v_balance;

  if v_balance is null then
    raise exception 'NO_PAID_CREDITS';
  end if;

  return v_balance;
end;
$$;

revoke all on function public.apply_stripe_credit_purchase(uuid,text,text,text,integer,integer,text) from public;
revoke all on function public.consume_paid_credit(uuid) from public;
grant execute on function public.apply_stripe_credit_purchase(uuid,text,text,text,integer,integer,text) to service_role;
grant execute on function public.consume_paid_credit(uuid) to service_role;
