create table if not exists public.daily_free_consultation_slots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  consultation_id text not null,
  usage_day date not null default ((timezone('America/Sao_Paulo', now()))::date),
  created_at timestamptz not null default now(),
  constraint daily_free_consultation_slots_user_consultation_key unique (user_id, consultation_id)
);

create index if not exists daily_free_consultation_slots_usage_day_idx
  on public.daily_free_consultation_slots (usage_day, created_at);

alter table public.daily_free_consultation_slots enable row level security;

create policy "users can read own daily free slots"
  on public.daily_free_consultation_slots
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create or replace function public.reserve_daily_free_consultation_slot(
  p_consultation_id text,
  p_daily_limit integer default 100
)
returns table (
  allowed boolean,
  used integer,
  daily_limit integer,
  usage_day date
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_day date := (timezone('America/Sao_Paulo', now()))::date;
  v_used integer := 0;
begin
  if v_user_id is null then
    raise exception 'AUTH_REQUIRED';
  end if;

  if p_daily_limit < 1 then
    raise exception 'INVALID_DAILY_LIMIT';
  end if;

  perform pg_advisory_xact_lock(hashtext('elaborae_daily_free_' || v_day::text));

  if exists (
    select 1
    from public.daily_free_consultation_slots
    where user_id = v_user_id
      and consultation_id = p_consultation_id
  ) then
    select count(*)::integer
      into v_used
    from public.daily_free_consultation_slots
    where usage_day = v_day;

    return query select true, v_used, p_daily_limit, v_day;
    return;
  end if;

  select count(*)::integer
    into v_used
  from public.daily_free_consultation_slots
  where usage_day = v_day;

  if v_used >= p_daily_limit then
    return query select false, v_used, p_daily_limit, v_day;
    return;
  end if;

  insert into public.daily_free_consultation_slots (user_id, consultation_id, usage_day)
  values (v_user_id, p_consultation_id, v_day);

  v_used := v_used + 1;
  return query select true, v_used, p_daily_limit, v_day;
end;
$$;

revoke all on function public.reserve_daily_free_consultation_slot(text, integer) from public;
grant execute on function public.reserve_daily_free_consultation_slot(text, integer) to authenticated;
