create table if not exists public.consultation_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  consultation_id text not null,
  completed_at timestamptz not null default now(),
  constraint consultation_usage_user_consultation_key unique (user_id, consultation_id)
);

create index if not exists consultation_usage_user_id_idx
  on public.consultation_usage (user_id, completed_at desc);

alter table public.consultation_usage enable row level security;

create policy "users can read own consultation usage"
  on public.consultation_usage
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "users can insert own consultation usage"
  on public.consultation_usage
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);
